### ISSUE TITLE
Improve the positioning of the footer

### ISSUE THREAD

**Issue by InnocentusLime** [InnocentusLime/innocentusLime.github.io#15]
Add the following css to prevent footer from floating up:

```css
footer {
  padding_bottom: 20px;
}

#app {
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}
```
